spring:
  application:
    name: audit-service
  flyway:
    enabled: true
    baseline-on-migrate: true
  datasource:
    url: ${JDBC_URL}
    username: ${JDBC_USERNAME}
    password: ${JDBC_PASSWORD}
    hikari:
      maximum-pool-size: 10
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    client-id: ${spring.application.name}
    consumer:
      auto-offset-reset: earliest
      group-id: ${spring.application.name}
logging:
  level:
    Exposed: debug
service:
  account-transaction-added-topic: ${SERVICE_ACCOUNT_TRANSACTION_ADDED_TOPIC}